### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Ogekuri** [jtsiomb/3dxdisp#2]
Did you have also create a script to generate the logo.h from a image (png/bmp/..) file?

Ciao,
Francesco.

**Comment by jtsiomb** [comment]
I think I used GIMP to convert to black&white with dithering, and then exported it as a "C header file". The format of a test image I just exported like that, looks identical to what i have in 3dxdisp.

**Comment by Ogekuri** [comment]
Thanks! I try with GIMP. Do you remember which is size in pixel of the image?

**Comment by jtsiomb** [comment]
Certainly, it's in the example program: 240x64

**Comment by Ogekuri** [comment]
Many thanks! It's work!

**Comment by jtsiomb** [comment]
Also I just added a new program in the repo, called 3dximage, which reads common image files and displays them on the device. See its own `3dximage/README.md` and `./3dximage -help` for build instructions and usage details.
